# -*- coding: utf-8 -*-
"""Azmitha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OVcbB5Juk9TEkr4Wx08wFJ26oEY9SOBP

# Human-in-the-Loop Data Drift Detection and Validation in Tabular Machine Learning Systems
## IEEE-CIS Fraud Detection — Complete End-to-End Pipeline

**Author:** Azmitha  
**Dissertation Topic:** Human-in-the-Loop Data Drift Detection and Validation in Tabular ML Systems  
**Dataset:** IEEE-CIS Fraud Detection (Kaggle)

---

## Pipeline Overview

This notebook implements a complete, production-realistic machine learning pipeline for fraud detection that demonstrates how **data drift** can be detected statistically and validated by a **human domain expert** before retraining decisions are made.

| Phase | Description |
|-------|-------------|
| **Phase 0** | Library imports and Google Drive setup |
| **Phase 1** | Data loading, merging, encoding, and saving |
| **Phase 1.5** | Exploratory Data Analysis (EDA) |
| **Phase 2** | Time-based train/test split (Reference vs Candidate) |
| **Phase 3** | Baseline LightGBM model training and evaluation |
| **Phase 4** | Applying baseline model to production (candidate) data |
| **Phase 5** | Statistical drift detection — KS Test, Chi-Square, PSI |
| **Phase 6** | Human-in-the-Loop expert validation via interactive widget |
| **Phase 7** | Model retraining and before/after performance comparison |

---

## Why This Approach Matters

In real-world fraud detection systems, a model is trained on **historical data** and deployed to classify future transactions. Over time, the statistical properties of incoming transactions change — this is called **data drift**. If left undetected, drift silently degrades model performance, leading to missed fraud cases.

This project addresses that problem by:
1. Detecting drift statistically using multiple complementary tests
2. Presenting drifted features to a **human domain expert** for business validation
3. Letting the human decide which drifted features actually matter for retraining
4. Retraining only when the expert confirms systemic, business-critical drift

This human-in-the-loop approach is more reliable than fully automated retraining because not all statistical drift is operationally meaningful.

---
## Phase 0 — Library Imports and Environment Setup

All required libraries are imported in a single cell at the top of the notebook. This is standard software engineering practice — it makes dependencies clear, avoids hidden import errors mid-run, and ensures the environment is fully configured before any data processing begins.

Google Drive is mounted **once** here. Mounting it multiple times across cells (as is common in auto-generated Colab notebooks) causes warnings and occasionally authentication errors.
"""

from google.colab import drive
drive.mount('/content/drive')
print("Google Drive mounted successfully.")

# ── Core Data & Numerics ──────────────────────────────────────
import pandas as pd
import numpy as np
import gc        # garbage collection — important for large datasets
import time
import joblib    # for saving and loading trained models

# ── Visualisation ─────────────────────────────────────────────
import matplotlib.pyplot as plt
from matplotlib.patches import Patch

# ── Statistical Tests for Drift Detection ─────────────────────
from scipy import stats
from scipy.stats import chi2_contingency

# ── Machine Learning ──────────────────────────────────────────
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    roc_auc_score,
    classification_report,
    RocCurveDisplay,
    PrecisionRecallDisplay,
    ConfusionMatrixDisplay,
    precision_score,
    recall_score,
    f1_score
)
import lightgbm as lgb

# ── Human-in-the-Loop Interactive Widget ──────────────────────
import ipywidgets as widgets
from IPython.display import display, clear_output

print("All libraries imported successfully.")

"""---
## Phase 1 — Data Loading, Merging, Encoding and Saving

### Dataset Background

The IEEE-CIS Fraud Detection dataset from Kaggle consists of two separate files:

- **train_transaction.csv** — ~590,540 rows, 394 columns. Contains core transactional features such as transaction amount, timestamp, product type, card details, and 300+ anonymised V-features engineered by Vesta Corporation.
- **train_identity.csv** — ~144,233 rows, 41 columns. Contains device and identity information for a subset of transactions.

Not every transaction has identity data, which is why we use a **left join** on `TransactionID`. This preserves all transactions even when no identity information exists (identity fields become NaN for unmatched rows).

### Target Variable

`isFraud` → 0 = Legitimate transaction, 1 = Fraudulent transaction

---

### Step 1.1 — Load and Merge
"""

data_path = '/content/drive/MyDrive/fraud_project/data'

print("Loading transaction data...")
train_transaction = pd.read_csv(f'{data_path}/train_transaction.csv')
print(f"  train_transaction shape : {train_transaction.shape}")

print("Loading identity data...")
train_identity = pd.read_csv(f'{data_path}/train_identity.csv')
print(f"  train_identity shape    : {train_identity.shape}")

# Left join — keeps all transactions, adds identity columns where available
df = pd.merge(train_transaction, train_identity, on='TransactionID', how='left')
print(f"\nMerged dataset shape : {df.shape}")
print(f"Identity rows matched  : {df['id_01'].notna().sum():,} of {df.shape[0]:,} transactions")

# Free memory — these large dataframes are no longer needed
del train_transaction, train_identity
gc.collect()
print("\nOriginal dataframes deleted from memory.")

"""### Step 1.2 — Categorical Encoding

All object (text) columns are filled with the string `'Unknown'` where values are missing, then converted to numeric codes using Label Encoding. This is necessary because LightGBM and most ML libraries require numeric input.

**Important design decision:** A **separate LabelEncoder instance is created for each column**. This matters because:
- Each encoder remembers the mapping for its own column independently
- Encoders are stored in a dictionary so we can look up or reverse any mapping later
- Using a single shared encoder (a common mistake) causes each column to silently overwrite the previous mapping, making inverse transformation impossible

**Note on encoding scope:** Label encoding is applied to the full merged dataset before the time-based split. In a strict production deployment, encoders would be fitted only on reference data and then used to `transform` candidate data. For this dissertation, encoding the full dataset is acceptable because the label mappings are category-to-integer assignments that do not derive statistical information from the target variable or future distributions — they are purely structural. The imputation step (Phase 2) correctly addresses the statistically meaningful leakage risk.
"""

# Step 1: Fill categorical missing values with 'Unknown'
# This is safe to do on the full dataset — 'Unknown' is not a numeric value
# and does not carry any distributional information from future data
cat_cols = df.select_dtypes(include=['object']).columns.tolist()
df[cat_cols] = df[cat_cols].fillna('Unknown')
print(f"Categorical columns filled with 'Unknown': {len(cat_cols)}")

# Step 2: Label encode each column with its own dedicated encoder
# We store all encoders in a dictionary for future use (e.g. inverse transform)
encoders = {}
for col in cat_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))
    encoders[col] = le

gc.collect()
print(f"Label encoding complete. {len(encoders)} separate encoders created and stored.")
print("Sample encodings (first 3 categorical columns):")
for col in list(encoders.keys())[:3]:
    print(f"  {col}: classes = {list(encoders[col].classes_[:5])} ...")

"""### Step 1.3 — Memory Optimisation via Downcasting

The merged dataset with 400+ columns consumes significant RAM. Downcasting numeric types from 64-bit to the smallest sufficient type (e.g. float64 → float32, int64 → int8/int16/int32) typically reduces memory usage by 40–60% with no loss of meaningful precision for this dataset.

**Important note on numeric imputation:** We do **not** fill numeric missing values here on the full dataset. Filling missing values using statistics (e.g. median) computed on the entire dataset — including future/candidate data — would constitute **data leakage**: the model would indirectly "see" information from future transactions during training. Instead, numeric imputation is performed after the time-based split in Phase 2, using statistics computed only from the reference (training) data.
"""

# Downcast float64 → float32
float_cols = df.select_dtypes(include=['float64']).columns
for col in float_cols:
    df[col] = df[col].astype(np.float32)

# Downcast int64 → smallest possible integer type
int_cols = df.select_dtypes(include=['int64']).columns
for col in int_cols:
    df[col] = pd.to_numeric(df[col], downcast='integer')

gc.collect()
memory_mb = round(df.memory_usage(deep=True).sum() / 1e6, 2)
print(f"Downcasting complete.")
print(f"  Float columns downcasted : {len(float_cols)}")
print(f"  Int columns downcasted   : {len(int_cols)}")
print(f"  Current memory usage     : {memory_mb} MB")

# Save the cleaned (but not yet imputed) dataset
save_path = '/content/drive/MyDrive/fraud_project/final_clean_dataset.csv'
df.to_csv(save_path, index=False)
print(f"\nClean dataset saved to Drive.")
print(f"Final shape: {df.shape}")

"""---
## Phase 1.5 — Exploratory Data Analysis (EDA)

Before building any model, it is essential to deeply understand the dataset. EDA helps us uncover patterns, identify anomalies, understand feature distributions, and make informed decisions throughout the modelling process.

We cover:
1. Basic dataset statistics
2. Class imbalance analysis
3. Transaction amount distribution
4. Missing value analysis
5. Feature correlation with the target
6. Fraud rate over time
7. Fraud by product type and card type
8. Outlier detection

---

### Step 1.5.1 — Basic Dataset Statistics
"""

print("  DATASET OVERVIEW")

print(f"  Total Rows        : {df.shape[0]:,}")
print(f"  Total Columns     : {df.shape[1]:,}")
print(f"  Memory Usage      : {round(df.memory_usage(deep=True).sum() / 1e6, 2)} MB")
print(f"  Duplicate Rows    : {df.duplicated().sum():,}")
print()
print("Data Types Present:")
print(df.dtypes.value_counts())
print()
print("First 5 rows sample:")
print(df[['TransactionID','TransactionAmt','ProductCD','isFraud']].head())

"""### Step 1.5.2 — Class Imbalance Analysis

Fraud detection datasets are inherently imbalanced — fraudulent transactions represent only a tiny fraction of all transactions. This is critical to understand before model training because:

- A naive model that predicts **everything as legitimate** would achieve very high accuracy (e.g. 96.5%) while completely failing to detect fraud
- We must use techniques like `scale_pos_weight` in LightGBM to compensate for this imbalance
- Evaluation metrics like **ROC-AUC** and **F1-Score** are more meaningful than raw accuracy for imbalanced data
"""

fraud_counts = df['isFraud'].value_counts()
total    = len(df)
legit    = fraud_counts.get(0, 0)
fraud    = fraud_counts.get(1, 0)
legit_pct = round(legit / total * 100, 2)
fraud_pct = round(fraud / total * 100, 2)
ratio     = round(legit / fraud, 1)

print("  CLASS IMBALANCE REPORT")
print(f"  Total Transactions  : {total:,}")
print(f"  Legitimate (0)      : {legit:,}  ({legit_pct}%)")
print(f"  Fraudulent (1)      : {fraud:,}  ({fraud_pct}%)")
print(f"  Imbalance Ratio     : {ratio}:1  (Legit : Fraud)")
print()
print("  Implication: A model predicting all-legitimate")
print(f"  would achieve {legit_pct}% accuracy but 0% fraud recall.")

fig, axes = plt.subplots(1, 2, figsize=(12, 4))
axes[0].bar(['Legitimate (0)', 'Fraudulent (1)'], [legit, fraud],
            color=['steelblue', 'crimson'], edgecolor='black')
axes[0].set_title('Class Distribution — Raw Count', fontweight='bold')
axes[0].set_ylabel('Number of Transactions')
for i, v in enumerate([legit, fraud]):
    axes[0].text(i, v + 1000, f'{v:,}', ha='center', fontweight='bold')

axes[1].pie([legit_pct, fraud_pct],
            labels=[f'Legitimate ({legit_pct}%)', f'Fraudulent ({fraud_pct}%)'],
            colors=['steelblue', 'crimson'],
            autopct='%1.2f%%', startangle=90,
            wedgeprops={'edgecolor': 'white', 'linewidth': 2})
axes[1].set_title('Class Distribution — Proportion', fontweight='bold')

plt.suptitle('isFraud Class Imbalance Analysis', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

"""### Step 1.5.3 — Transaction Amount Analysis

Transaction amount (`TransactionAmt`) is one of the most intuitive fraud indicators. Fraudsters often make either very small test transactions (to verify a card works) or very large unauthorised transfers. The raw distribution is heavily right-skewed, so we also apply a log transformation to better visualise the shape.
"""

fig, axes = plt.subplots(2, 2, figsize=(14, 10))

axes[0,0].hist(df['TransactionAmt'], bins=100, color='steelblue', edgecolor='none')
axes[0,0].set_title('Raw TransactionAmt Distribution', fontweight='bold')
axes[0,0].set_xlabel('Amount (USD)')
axes[0,0].set_ylabel('Count')

axes[0,1].hist(np.log1p(df['TransactionAmt']), bins=50, color='green', edgecolor='none')
axes[0,1].set_title('Log(1+TransactionAmt) Distribution', fontweight='bold')
axes[0,1].set_xlabel('Log Amount')
axes[0,1].set_ylabel('Count')

df[df['isFraud']==0]['TransactionAmt'].apply(np.log1p).hist(
    bins=50, ax=axes[1,0], color='steelblue', alpha=0.6, label='Legitimate')
df[df['isFraud']==1]['TransactionAmt'].apply(np.log1p).hist(
    bins=50, ax=axes[1,0], color='crimson', alpha=0.6, label='Fraudulent')
axes[1,0].set_title('Log Amount: Legitimate vs Fraudulent', fontweight='bold')
axes[1,0].set_xlabel('Log Amount')
axes[1,0].legend()

df.boxplot(column='TransactionAmt', by='isFraud', ax=axes[1,1])
axes[1,1].set_title('Transaction Amount by Class', fontweight='bold')
axes[1,1].set_xlabel('isFraud (0=Legitimate, 1=Fraudulent)')

print("Transaction Amount Statistics by Class:")
print(df.groupby('isFraud')['TransactionAmt'].describe().round(2))

plt.tight_layout()
plt.show()

"""### Step 1.5.4 — Missing Value Analysis

Even after categorical columns were filled with 'Unknown', numeric columns still contain missing values. We visualise which columns are most affected. High missingness in certain columns may affect model quality and drift detection later.
"""

missing     = df.isnull().sum()
missing_pct = (missing / len(df)) * 100
missing_df  = pd.DataFrame({'Missing Count': missing, 'Missing %': missing_pct})
missing_df  = missing_df[missing_df['Missing %'] > 0].sort_values('Missing %', ascending=False)

print(f"Columns with missing numeric values : {len(missing_df)}")
print(f"Total missing values                 : {df.isnull().sum().sum():,}")

if len(missing_df) > 0:
    plt.figure(figsize=(14, 5))
    missing_df.head(25)['Missing %'].plot(kind='bar', color='crimson', edgecolor='black')
    plt.title('Top 25 Columns by Missing Value Percentage', fontweight='bold')
    plt.xlabel('Column')
    plt.ylabel('Missing %')
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    plt.show()
    print("\nTop 10 most missing columns:")
    print(missing_df.head(10).to_string())
else:
    print("No missing numeric values found.")

"""### Step 1.5.5 — Feature Correlation with isFraud

Pearson correlation tells us which features have the strongest linear relationship with the fraud label. Features with high absolute correlation are likely to be important predictors. This analysis also guides us in Phase 6 when we need to explain to the human expert which features are most business-relevant.
"""

# Use numeric-only columns to avoid FutureWarning in newer pandas versions
corr = df.select_dtypes(include=[np.number]).corr()['isFraud'].drop('isFraud')
corr = corr.abs().sort_values(ascending=False)

print("Top 20 Features Most Correlated with isFraud (absolute Pearson):")
print(corr.head(20).to_string())

plt.figure(figsize=(13, 5))
corr.head(20).plot(kind='bar', color='darkorange', edgecolor='black')
plt.title('Top 20 Features — Absolute Correlation with isFraud', fontweight='bold')
plt.xlabel('Feature')
plt.ylabel('Absolute Pearson Correlation')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""### Step 1.5.6 — Fraud Rate Over Time

`TransactionDT` is a timedelta in seconds from a reference point. It encodes the chronological ordering of transactions. Analysing how the fraud rate changes over time is critical for this dissertation because it:

1. Confirms that temporal patterns exist in the data
2. Motivates why a **time-based split** is more realistic than a random split
3. Provides early visual evidence that data drift (changing fraud patterns over time) may be present
"""

df['DT_bin'] = pd.cut(df['TransactionDT'], bins=50)
time_fraud   = df.groupby('DT_bin', observed=True)['isFraud'].mean()

plt.figure(figsize=(15, 5))
time_fraud.plot(kind='line', color='crimson', linewidth=2)
plt.title('Fraud Rate Over Time (TransactionDT Bins)', fontweight='bold')
plt.xlabel('Time Bins (TransactionDT seconds)')
plt.ylabel('Fraud Rate (proportion)')
plt.xticks(rotation=45, ha='right')
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

print("TransactionDT Summary Statistics:")
print(df['TransactionDT'].describe().round(2))
print()
print("Interpretation: Variation in fraud rate over time confirms temporal")
print("patterns exist, motivating the time-based train/test split in Phase 2.")

"""### Step 1.5.7 — Outlier Detection in Transaction Amount

Outliers in transaction amounts can distort model learning and also have different fraud rates compared to typical transactions. We use the **IQR (Interquartile Range) method** — a robust, distribution-agnostic technique — to identify outliers.
"""

Q1    = df['TransactionAmt'].quantile(0.25)
Q3    = df['TransactionAmt'].quantile(0.75)
IQR   = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df['TransactionAmt'] < lower) | (df['TransactionAmt'] > upper)]

print("  OUTLIER DETECTION REPORT (IQR Method)")
print(f"  Q1 (25th percentile)  : {Q1:.2f}")
print(f"  Q3 (75th percentile)  : {Q3:.2f}")
print(f"  IQR                   : {IQR:.2f}")
print(f"  Lower bound           : {lower:.2f}")
print(f"  Upper bound           : {upper:.2f}")
print(f"  Total outliers        : {len(outliers):,}  ({round(len(outliers)/len(df)*100,2)}%)")
print(f"  Fraud in outliers     : {outliers['isFraud'].sum():,}")
print(f"  Fraud rate in outliers: {round(outliers['isFraud'].mean()*100, 2)}%")
print(f"  Fraud rate overall    : {round(df['isFraud'].mean()*100, 2)}%")
print()
print("Interpretation: If fraud rate in outliers > overall fraud rate,")
print("extreme transaction amounts are a meaningful fraud signal.")

"""---
## Phase 2 — Time-Based Split: Reference vs Candidate Data

### Why Time-Based Splitting?

A **random split** would not simulate real-world model deployment. In production, a model is trained on **past** data and evaluated on **future** data — never the reverse. Random splitting allows future information to leak into training, making the setup unrealistic for drift detection.

We sort all transactions chronologically by `TransactionDT` and split:
- **Reference Set (70%)** — Older transactions — used for model training
- **Candidate Set (30%)** — Newer transactions — simulates production data arriving after deployment

### Preventing Data Leakage in Imputation

**This is a critical methodological step.** Numeric missing values must be filled using statistics (median) computed **only from the reference/training data**. The same medians are then applied to the candidate data. This mirrors what would happen in a real deployment scenario — the imputation statistics from training time are saved and applied to all future incoming data.

If we computed medians on the entire combined dataset before splitting, the training data would indirectly "know" about the statistical properties of future transactions — this is data leakage.
"""

# Sort all transactions chronologically by TransactionDT
df_sorted = df.sort_values('TransactionDT').reset_index(drop=True)
split_idx = int(len(df_sorted) * 0.70)

reference = df_sorted.iloc[:split_idx].reset_index(drop=True)
candidate = df_sorted.iloc[split_idx:].reset_index(drop=True)

print("  TIME-BASED SPLIT REPORT")
print(f"  Total rows         : {len(df_sorted):,}")
print(f"  Reference (train)  : {len(reference):,} rows  ({round(len(reference)/len(df_sorted)*100,1)}%)")
print(f"  Candidate (prod)   : {len(candidate):,} rows  ({round(len(candidate)/len(df_sorted)*100,1)}%)")
print()
print(f"  Reference DT range : {reference['TransactionDT'].min()} → {reference['TransactionDT'].max()}")
print(f"  Candidate DT range : {candidate['TransactionDT'].min()} → {candidate['TransactionDT'].max()}")
print()
print(f"  Reference fraud rate : {round(reference['isFraud'].mean()*100, 2)}%")
print(f"  Candidate fraud rate : {round(candidate['isFraud'].mean()*100, 2)}%")

# Numeric imputation using REFERENCE medians only
# This prevents data leakage: the candidate set's distribution does NOT
# influence the imputation values used during training

num_cols          = reference.select_dtypes(include=[np.number]).columns.tolist()
reference_medians = reference[num_cols].median().fillna(0)   # computed from training data only; fillna(0) guards all-NaN columns

reference[num_cols] = reference[num_cols].fillna(reference_medians)
candidate[num_cols] = candidate[num_cols].fillna(reference_medians)  # same medians applied

print("Numeric imputation complete.")
print("  Method: Median imputation using reference data statistics only")
print("  The same medians are applied to candidate data (no leakage)")
print()
print(f"  Missing values in reference after imputation : {reference.isnull().sum().sum()}")
print(f"  Missing values in candidate after imputation : {candidate.isnull().sum().sum()}")

# Save both sets to Drive for use in later phases
reference.to_csv('/content/drive/MyDrive/fraud_project/reference.csv', index=False)
candidate.to_csv('/content/drive/MyDrive/fraud_project/candidate.csv', index=False)
print()
print("Reference and candidate datasets saved to Drive.")# ── Numeric imputation using REFERENCE medians only ─────────────────────────
# This prevents data leakage: the candidate set's distribution does NOT
# influence the imputation values used during training

num_cols          = reference.select_dtypes(include=[np.number]).columns.tolist()
reference_medians = reference[num_cols].median().fillna(0)   # computed from training data only; fillna(0) guards all-NaN columns

reference[num_cols] = reference[num_cols].fillna(reference_medians)
candidate[num_cols] = candidate[num_cols].fillna(reference_medians)  # same medians applied

print("Numeric imputation complete.")
print("  Method: Median imputation using reference data statistics only")
print("  The same medians are applied to candidate data (no leakage)")
print()
print(f"  Missing values in reference after imputation : {reference.isnull().sum().sum()}")
print(f"  Missing values in candidate after imputation : {candidate.isnull().sum().sum()}")

# Save both sets to Drive for use in later phases
reference.to_csv('/content/drive/MyDrive/fraud_project/reference.csv', index=False)
candidate.to_csv('/content/drive/MyDrive/fraud_project/candidate.csv', index=False)
print()
print("Reference and candidate datasets saved to Drive.")

"""---
## Phase 3 — Baseline Model Training

We train a **LightGBM** (Light Gradient Boosting Machine) classifier on the reference dataset. LightGBM is chosen because:
- It handles large datasets (500K+ rows, 400+ columns) efficiently
- It natively supports class imbalance via `scale_pos_weight`
- It uses early stopping to prevent overfitting
- It is widely used in production fraud detection systems

### Why LightGBM over other models?

Random Forest and standard Gradient Boosting are slower and more memory-intensive on this scale. Neural networks require more feature engineering and are harder to interpret. LightGBM provides an excellent balance of speed, performance, and interpretability via feature importance scores.

### Handling Class Imbalance

With a fraud rate of ~3.5%, we use `scale_pos_weight = count(legitimate) / count(fraud)`. This tells LightGBM to penalise misclassifying fraud cases more heavily, effectively upweighting the minority class during training.

### Hyperparameter Choices

The following hyperparameters are used and justified as follows:

- `n_estimators=300` — A standard starting value for tabular datasets of this size; early stopping (patience=30) prevents overfitting if convergence occurs earlier.
- `learning_rate=0.05` — A conservative rate that, combined with early stopping, provides stable convergence without requiring exhaustive grid search.
- `max_depth=8` — Controls tree complexity; depth of 8 is a well-established default for fraud detection tasks with hundreds of features.
- `num_leaves=31` — LightGBM's default; appropriate for this dataset size without excessive memory usage.

Full hyperparameter optimisation (e.g. via grid search or Bayesian optimisation) is outside the scope of this dissertation, which focuses on the drift detection and HITL validation pipeline rather than model tuning.

---

### Step 3.1 — Load Reference Data and Train the Model
"""

ref = pd.read_csv('/content/drive/MyDrive/fraud_project/reference.csv', low_memory=False)

# Remove columns that should not be used as features
drop_cols = [c for c in ['TransactionID', 'TransactionDT', 'isFraud', 'DT_bin'] if c in ref.columns]
X = ref.drop(columns=drop_cols)
y = ref['isFraud']
del ref; gc.collect()

# Stratified split ensures both train and val sets maintain the same fraud ratio
X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)
del X, y; gc.collect()

# Calculate class imbalance ratio for scale_pos_weight
fraud_count = y_train.sum()
legit_count = (y_train == 0).sum()
scale       = round(legit_count / fraud_count, 2)
print("  TRAINING SET SUMMARY")
print(f"  Training samples   : {len(X_train):,}")
print(f"  Validation samples : {len(X_val):,}")
print(f"  Fraud in train     : {fraud_count:,}")
print(f"  Legit in train     : {legit_count:,}")
print(f"  scale_pos_weight   : {scale}  (applied to compensate for imbalance)")

lgb_model = lgb.LGBMClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=8,
    num_leaves=31,
    scale_pos_weight=scale,
    random_state=42,
    n_jobs=-1,
    verbose=-1
)

print()
print("Training LightGBM baseline model...")
start = time.time()
lgb_model.fit(
    X_train, y_train,
    eval_set=[(X_val, y_val)],
    callbacks=[
        lgb.early_stopping(stopping_rounds=30, verbose=False),
        lgb.log_evaluation(50)
    ]
)
elapsed = round(time.time() - start, 2)
del X_train, y_train; gc.collect()
print(f"Training complete in {elapsed} seconds.")

"""### Step 3.2 — Classification Threshold Selection via F1-Maximisation

LightGBM (like all probabilistic classifiers) outputs a **probability** that each transaction is fraudulent. To convert probabilities into binary predictions (fraud / not fraud), we need a **classification threshold**.

A naive choice is 0.5, but this is inappropriate for imbalanced datasets. With only 3.5% fraud cases, the model needs a lower threshold to capture enough fraud cases at the cost of some false positives.

**Our approach:** We evaluate every threshold from 0.01 to 0.50 in steps of 0.01 and select the one that **maximises the F1 score** on the validation set. F1 is the harmonic mean of precision and recall, making it a balanced metric for imbalanced classification. This ensures the threshold choice is data-driven and reproducible — not arbitrary.
"""

y_pred_proba = lgb_model.predict_proba(X_val)[:, 1]

# Evaluate all thresholds and pick the one maximising validation F1 score
thresholds     = np.arange(0.01, 0.50, 0.01)
f1_scores_list = [f1_score(y_val, (y_pred_proba >= t).astype(int)) for t in thresholds]
best_threshold = thresholds[np.argmax(f1_scores_list)]

print(f"Threshold Selection — F1 Maximisation on Validation Set")
print(f"  Best threshold : {round(best_threshold, 2)}")
print(f"  Best F1 score  : {round(max(f1_scores_list), 4)}")

plt.figure(figsize=(11, 4))
plt.plot(thresholds, f1_scores_list, color='steelblue', linewidth=2)
plt.axvline(x=best_threshold, color='crimson', linestyle='--', linewidth=2,
            label=f'Best Threshold = {round(best_threshold, 2)}')
plt.fill_between(thresholds, f1_scores_list, alpha=0.1, color='steelblue')
plt.title('F1 Score vs Classification Threshold (Validation Set)', fontweight='bold')
plt.xlabel('Threshold')
plt.ylabel('F1 Score')
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

# Apply the best threshold to produce binary predictions
y_pred = (y_pred_proba >= best_threshold).astype(int)

# Store all baseline metrics as variables — used for comparison in later phases
roc_ref       = roc_auc_score(y_val, y_pred_proba)
precision_ref = precision_score(y_val, y_pred)
recall_ref    = recall_score(y_val, y_pred)
f1_ref        = f1_score(y_val, y_pred)

print()
print("  BASELINE MODEL PERFORMANCE — VALIDATION SET")
print(f"  ROC-AUC   : {round(roc_ref, 4)}")
print(f"  Precision : {round(precision_ref, 4)}")
print(f"  Recall    : {round(recall_ref, 4)}")
print(f"  F1-Score  : {round(f1_ref, 4)}")
print(f"  Threshold : {round(best_threshold, 2)}  (F1-maximised)")
print()
print(classification_report(y_val, y_pred, target_names=['Legitimate', 'Fraudulent']))

"""### Step 3.3 — Model Visualisations

Four diagnostic visualisations are produced:
1. **Confusion Matrix** — shows exact counts of true/false positives and negatives
2. **ROC Curve** — plots true positive rate vs false positive rate at all thresholds
3. **Precision-Recall Curve** — particularly important for imbalanced datasets
4. **Feature Importance** — shows which features the model relies on most for fraud detection
"""

fig, axes = plt.subplots(2, 2, figsize=(14, 11))

# Confusion Matrix
ConfusionMatrixDisplay.from_predictions(
    y_val, y_pred,
    display_labels=['Legitimate', 'Fraudulent'],
    cmap='Blues', ax=axes[0, 0])
axes[0, 0].set_title('Confusion Matrix — Validation Set', fontweight='bold')

# ROC Curve
RocCurveDisplay.from_predictions(y_val, y_pred_proba, ax=axes[0, 1])
axes[0, 1].set_title(f'ROC Curve  (AUC = {round(roc_ref, 4)})', fontweight='bold')
axes[0, 1].plot([0,1],[0,1],'k--',alpha=0.4)

# Precision-Recall Curve
PrecisionRecallDisplay.from_predictions(y_val, y_pred_proba, ax=axes[1, 0])
axes[1, 0].set_title('Precision-Recall Curve — Validation Set', fontweight='bold')

# Feature Importance
feat_imp = pd.Series(
    lgb_model.feature_importances_,
    index=X_val.columns
).sort_values(ascending=False).head(20)
feat_imp.plot(kind='bar', ax=axes[1, 1], color='steelblue', edgecolor='black')
axes[1, 1].set_title('Top 20 Feature Importances (LightGBM)', fontweight='bold')
axes[1, 1].set_xlabel('Feature')
axes[1, 1].set_ylabel('Importance Score')
axes[1, 1].tick_params(axis='x', rotation=45)

plt.suptitle('LightGBM Baseline Model — Complete Performance Overview',
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

# Save baseline model to Drive
joblib.dump(lgb_model, '/content/drive/MyDrive/fraud_project/lgb_baseline_model.pkl')
print("Baseline model saved to Drive.")

"""---
## Phase 4 — Evaluating the Baseline Model on Production (Candidate) Data

In a real-world deployment scenario, a model trained on historical data is applied to new incoming transactions. Over time, the distribution of those transactions changes — customers adopt new devices, fraud patterns evolve, product mixes shift — and the model's performance begins to degrade. This degradation is the observable consequence of **data drift**.

In this phase, we apply our baseline model (trained on reference data) to the candidate (production) dataset to measure whether performance has dropped. A significant drop is our primary signal that drift has occurred and retraining should be considered.

---

### Step 4.1 — Load Candidate Data and Apply Baseline Model
"""

candidate = pd.read_csv('/content/drive/MyDrive/fraud_project/candidate.csv', low_memory=False)
drop_cols = [c for c in ['TransactionID', 'TransactionDT', 'isFraud', 'DT_bin'] if c in candidate.columns]
X_cand = candidate.drop(columns=drop_cols)
y_cand = candidate['isFraud']
del candidate; gc.collect()

# Load the saved baseline model and apply it to candidate data
lgb_model    = joblib.load('/content/drive/MyDrive/fraud_project/lgb_baseline_model.pkl')
y_cand_proba = lgb_model.predict_proba(X_cand)[:, 1]
y_cand_pred  = (y_cand_proba >= best_threshold).astype(int)

# Compute candidate performance metrics
roc_cand       = roc_auc_score(y_cand, y_cand_proba)
precision_cand = precision_score(y_cand, y_cand_pred)
recall_cand    = recall_score(y_cand, y_cand_pred)
f1_cand        = f1_score(y_cand, y_cand_pred)

print("  REFERENCE vs CANDIDATE — PERFORMANCE COMPARISON")
print(f"  {'Metric':<12} {'Reference':>12} {'Candidate':>12} {'Change':>10}")
print(f"  {'ROC-AUC':<12} {round(roc_ref,4):>12} {round(roc_cand,4):>12} {round(roc_cand-roc_ref,4):>+10}")
print(f"  {'Precision':<12} {round(precision_ref,4):>12} {round(precision_cand,4):>12} {round(precision_cand-precision_ref,4):>+10}")
print(f"  {'Recall':<12} {round(recall_ref,4):>12} {round(recall_cand,4):>12} {round(recall_cand-recall_ref,4):>+10}")
print(f"  {'F1-Score':<12} {round(f1_ref,4):>12} {round(f1_cand,4):>12} {round(f1_cand-f1_ref,4):>+10}")
print()
print("  Interpretation: A negative change in ROC-AUC indicates")
print("  the model generalises less well to newer transactions,")
print("  which is consistent with data drift having occurred.")

"""### Step 4.2 — Statistical Significance of the Performance Drop

Observing a drop in ROC-AUC from reference to candidate data does not automatically confirm that drift has caused a meaningful degradation. The drop could be due to random variation between the two splits.

We use **Bootstrap Confidence Intervals** on the candidate ROC-AUC to assess whether the observed performance drop is within the range of random sampling variation. The method:
1. Resamples the **candidate** predictions with replacement (1000 iterations) independently, and also resamples the reference (validation) predictions
2. Computes ROC-AUC on each resample for both sets
3. Builds a 95% confidence interval around the distribution of differences

If the 95% CI of ROC-AUC differences is **entirely below zero**, the candidate set performs worse than reference in a way that is unlikely to be explained by random sampling variation alone. This provides evidence — though not formal hypothesis-test significance — that drift has meaningfully degraded model performance.

**Note:** McNemar's test (a common alternative) is only valid when comparing predictions on the **same set of samples** with two different classifiers. Here we are comparing the same classifier on **two different datasets** (reference vs candidate), so bootstrap confidence intervals are the appropriate method.
"""

np.random.seed(42)
n_bootstrap = 1000
roc_diffs   = []

for _ in range(n_bootstrap):
    # Resample candidate predictions with replacement
    idx         = np.random.choice(len(y_cand), size=len(y_cand), replace=True)
    y_cand_boot = np.array(y_cand)[idx]
    p_cand_boot = y_cand_proba[idx]

    # Resample reference (validation) predictions with replacement
    idx_ref     = np.random.choice(len(y_val), size=len(y_val), replace=True)
    y_val_boot  = np.array(y_val)[idx_ref]
    p_val_boot  = y_pred_proba[idx_ref]

    try:
        roc_ref_b  = roc_auc_score(y_val_boot,  p_val_boot)
        roc_cand_b = roc_auc_score(y_cand_boot, p_cand_boot)
        roc_diffs.append(roc_cand_b - roc_ref_b)
    except ValueError:
        pass  # skip iteration if bootstrap sample has only one class

ci_lower = np.percentile(roc_diffs, 2.5)
ci_upper = np.percentile(roc_diffs, 97.5)
observed_diff = roc_cand - roc_ref

print("  BOOTSTRAP SIGNIFICANCE TEST — ROC-AUC DROP")
print(f"  Observed ROC-AUC difference  : {round(observed_diff, 4)}")
print(f"  95% Confidence Interval      : [{round(ci_lower,4)}, {round(ci_upper,4)}]")
print(f"  Bootstrap iterations         : {n_bootstrap}")
print()
if ci_upper < 0:
    print("  Result : 95% CI is entirely below zero (non-overlapping).")
    print("  Conclusion : The CI of ROC-AUC differences excludes zero,")
    print("               suggesting the performance drop is unlikely due to")
    print("               random sampling variation alone.")
else:
    print("  Result : 95% CI includes zero.")
    print("  Conclusion : The observed performance difference is within the range")
    print("               expected from random sampling variation.")

# Visualise the bootstrap distribution
plt.figure(figsize=(10, 4))
plt.hist(roc_diffs, bins=50, color='steelblue', edgecolor='none', alpha=0.8)
plt.axvline(x=observed_diff, color='crimson', linewidth=2, linestyle='--',
            label=f'Observed diff = {round(observed_diff,4)}')
plt.axvline(x=ci_lower, color='orange', linewidth=2, linestyle=':',
            label=f'95% CI lower = {round(ci_lower,4)}')
plt.axvline(x=ci_upper, color='orange', linewidth=2, linestyle=':',
            label=f'95% CI upper = {round(ci_upper,4)}')
plt.axvline(x=0, color='black', linewidth=1.5, linestyle='-', alpha=0.5, label='Zero (no difference)')
plt.title('Bootstrap Distribution of ROC-AUC Difference (Candidate − Reference)', fontweight='bold')
plt.xlabel('ROC-AUC Difference')
plt.ylabel('Frequency')
plt.legend()
plt.tight_layout()
plt.show()

"""### Step 4.3 — Visual Performance Comparison"""

metrics     = ['ROC-AUC', 'Precision', 'Recall', 'F1-Score']
ref_scores  = [round(roc_ref,4), round(precision_ref,4), round(recall_ref,4), round(f1_ref,4)]
cand_scores = [round(roc_cand,4), round(precision_cand,4), round(recall_cand,4), round(f1_cand,4)]
x = range(len(metrics)); width = 0.35

fig, ax = plt.subplots(figsize=(11, 5))
ax.bar([i-width/2 for i in x], ref_scores,  width, label='Reference (Train)', color='steelblue', edgecolor='black')
ax.bar([i+width/2 for i in x], cand_scores, width, label='Candidate (Production)', color='crimson', edgecolor='black')
ax.set_title('Baseline Model: Reference vs Candidate Performance', fontweight='bold')
ax.set_xticks(list(x)); ax.set_xticklabels(metrics, fontsize=12)
ax.set_ylabel('Score'); ax.set_ylim(0, 1); ax.legend(fontsize=11)
for i, (r, c) in enumerate(zip(ref_scores, cand_scores)):
    ax.text(i-width/2, r+0.01, str(r), ha='center', fontsize=9, fontweight='bold')
    ax.text(i+width/2, c+0.01, str(c), ha='center', fontsize=9, fontweight='bold')
plt.tight_layout(); plt.show()

"""---
## Phase 5 — Statistical Data Drift Detection

Now that we have confirmed a performance drop, we investigate **which specific features** have drifted. This is essential for the Human-in-the-Loop phase — the human expert needs to know exactly which features changed, by how much, and in what direction.

We use three complementary statistical methods:

| Method | Type | What it measures |
|--------|------|-----------------|
| **KS Test** | Numerical features | Whether two samples come from the same distribution |
| **Chi-Square Test** | Categorical features | Whether frequency distributions have changed |
| **PSI** | Numerical features | Magnitude of distribution shift |

Using all three methods provides cross-validation — a feature confirmed as drifted by multiple tests is more reliably flagged than one identified by a single test alone.

### Multiple Testing Correction (Bonferroni)

When running statistical tests on hundreds of features simultaneously, false positives accumulate. With 400+ features tested at α = 0.05, we would expect approximately 20 features to appear drifted by chance alone, even if there is no real drift.

The **Bonferroni correction** adjusts the significance threshold by dividing α by the number of tests: `α_corrected = 0.05 / number_of_tests`. This controls the **Family-Wise Error Rate (FWER)** — the probability of making even one false positive across all tests — at 5%.

---

### Step 5.1 — Load Datasets for Comparison
"""

ref  = pd.read_csv('/content/drive/MyDrive/fraud_project/reference.csv', low_memory=False)
cand = pd.read_csv('/content/drive/MyDrive/fraud_project/candidate.csv', low_memory=False)

drop_cols = ['TransactionID', 'TransactionDT', 'isFraud', 'DT_bin']
ref  = ref.drop(columns=[c for c in drop_cols if c in ref.columns])
cand = cand.drop(columns=[c for c in drop_cols if c in cand.columns])

print(f"Reference shape  : {ref.shape}")
print(f"Candidate shape  : {cand.shape}")
print()
print("Both datasets loaded. Feature-wise drift tests will now be applied.")

"""### Step 5.2 — KS Test on Numerical Features (with Bonferroni Correction)

The Kolmogorov-Smirnov (KS) test is a non-parametric test that measures the maximum absolute difference between the empirical cumulative distribution functions of two samples. It makes no assumptions about the underlying distribution, making it robust for the highly varied feature types in this dataset.

- **KS Statistic:** Higher values indicate greater distribution divergence
- **p-value:** Below the Bonferroni-corrected threshold → drift detected
"""

num_cols = ref.select_dtypes(include=[np.number]).columns.tolist()

# Bonferroni correction: divide significance level by number of simultaneous tests
n_tests          = len(num_cols)
bonferroni_alpha = 0.05 / n_tests

print("KS Test — Bonferroni Multiple Testing Correction")
print(f"  Total numerical features tested : {n_tests}")
print(f"  Original significance level     : 0.05")
print(f"  Bonferroni-corrected threshold  : {bonferroni_alpha:.8f}  (0.05 / {n_tests})")
print(f"  Interpretation: Only features with p-value < {bonferroni_alpha:.6f}")
print(f"  are flagged as drifted, to control false discoveries.")
print()

ks_results = []
for col in num_cols:
    stat, pval = stats.ks_2samp(ref[col].dropna(), cand[col].dropna())
    ks_results.append({
        'Feature'       : col,
        'KS Statistic'  : round(stat, 4),
        'P-Value'       : round(pval, 8),
        'Drift Detected': 'YES' if pval < bonferroni_alpha else 'NO'
    })

ks_df   = pd.DataFrame(ks_results).sort_values('KS Statistic', ascending=False)
drifted = len(ks_df[ks_df['Drift Detected']=='YES'])

print("  KS TEST RESULTS (Bonferroni-corrected)")
print(f"  Total features tested  : {len(ks_df)}")
print(f"  Drift confirmed        : {drifted}  ({round(drifted/len(ks_df)*100, 2)}%)")
print(f"  No significant drift   : {len(ks_df)-drifted}")
print()
print("Top 25 Most Drifted Numerical Features:")
print(ks_df.head(25).to_string(index=False))

"""### Step 5.3 — Chi-Square Test on Categorical Features (with Bonferroni Correction)

The Chi-Square test of independence assesses whether the frequency distribution of a categorical variable has changed between reference and candidate data. A significant result indicates the proportions of categories have shifted — e.g. the mix of card types or email domains used in transactions has changed.

Bonferroni correction is applied here as well, since we are testing multiple categorical features simultaneously.
"""

# Auto-detect categorical columns + known encoded categoricals
known_cats = ['ProductCD','card4','card6','P_emaildomain','R_emaildomain',
              'M1','M2','M3','M4','M5','M6','M7','M8','M9']
cat_cols   = list(set(
    ref.select_dtypes(include=['object']).columns.tolist() +
    [c for c in known_cats if c in ref.columns]
))
cat_cols = sorted([c for c in cat_cols if c in ref.columns and c in cand.columns])

# Bonferroni correction for categorical tests
chi_alpha_corrected = 0.05 / len(cat_cols)
print(f"Chi-Square Test — Bonferroni Correction Applied")
print(f"  Categorical features tested         : {len(cat_cols)}")
print(f"  Bonferroni-corrected alpha          : {chi_alpha_corrected:.4f}  (0.05 / {len(cat_cols)})")
print()

chi_results = []
for col in cat_cols:
    ref_counts  = ref[col].value_counts()
    cand_counts = cand[col].value_counts()
    all_cats    = set(ref_counts.index) | set(cand_counts.index)
    ref_freq    = [ref_counts.get(c, 0)  for c in all_cats]
    cand_freq   = [cand_counts.get(c, 0) for c in all_cats]
    try:
        stat, pval, _, _ = chi2_contingency(np.array([ref_freq, cand_freq]))
        chi_results.append({
            'Feature'        : col,
            'Chi2 Statistic' : round(stat, 4),
            'P-Value'        : round(pval, 6),
            'Drift Detected' : 'YES' if pval < chi_alpha_corrected else 'NO'
        })
    except Exception as e:
        print(f'  Chi2 skipped for {col}: {e}')

chi_df   = pd.DataFrame(chi_results).sort_values('Chi2 Statistic', ascending=False)
drifted_chi = len(chi_df[chi_df['Drift Detected']=='YES'])

print("  CHI-SQUARE TEST RESULTS (Bonferroni-corrected)")
print(f"  Features tested     : {len(chi_df)}")
print(f"  Drift confirmed     : {drifted_chi}")
print(f"  No significant drift: {len(chi_df)-drifted_chi}")
print()
print(chi_df.to_string(index=False))

"""### Step 5.4 — Population Stability Index (PSI) on Top Drifted Features

The Population Stability Index (PSI) is widely used in the banking and financial services industry to monitor model input distributions. Unlike the KS test which gives a binary yes/no, PSI provides a **continuous magnitude** of drift:

| PSI Value | Interpretation |
|-----------|----------------|
| PSI < 0.10 | Stable — no significant change |
| 0.10 ≤ PSI < 0.20 | Moderate change — monitor closely |
| PSI ≥ 0.20 | Significant shift — retraining recommended |

**Implementation note:** PSI is computed using **fixed-width bins** based on the reference data range. This is the standard industry method. An earlier version of this code incorrectly used quantile-based bins (percentile breakpoints), which always distributes the reference data equally across bins, making the reference PSI trivially zero and rendering the measure meaningless.
"""

def calculate_psi(ref_col, cand_col, bins=10):
    # Standard PSI using fixed-width bins based on reference column range.
    # PSI < 0.10  = Stable | 0.10-0.20 = Monitor | > 0.20 = Unstable
    ref_col, cand_col = np.array(ref_col), np.array(cand_col)
    col_min, col_max  = ref_col.min(), ref_col.max()

    if col_min == col_max:
        return 0.0   # No variation in this feature — PSI not meaningful

    # Fixed-width breakpoints spanning the reference range
    breakpoints = np.linspace(col_min, col_max, bins + 1)

    ref_counts  = np.histogram(ref_col,  bins=breakpoints)[0]
    cand_counts = np.histogram(cand_col, bins=breakpoints)[0]

    # Convert to proportions; add small epsilon to avoid log(0)
    ref_pct  = ref_counts  / len(ref_col)  + 1e-10
    cand_pct = cand_counts / len(cand_col) + 1e-10

    psi = np.sum((cand_pct - ref_pct) * np.log(cand_pct / ref_pct))
    return round(psi, 4)

# Apply PSI to the top 20 most drifted numerical features (by KS statistic)
top_ks_features = ks_df.head(20)['Feature'].tolist()

psi_results = []
for col in top_ks_features:
    if col in ref.columns and col in cand.columns:
        psi_val = calculate_psi(ref[col].dropna().values, cand[col].dropna().values)
        psi_results.append({
            'Feature'  : col,
            'PSI'      : psi_val,
            'Stability': 'Stable' if psi_val < 0.10 else ('Monitor' if psi_val < 0.20 else 'Unstable')
        })

psi_df = pd.DataFrame(psi_results).sort_values('PSI', ascending=False)

print("  PSI RESULTS — Fixed-Width Bins (Standard Method)")
print(f"  Stable   (PSI < 0.10)  : {len(psi_df[psi_df['Stability']=='Stable'])}")
print(f"  Monitor  (0.10-0.20)   : {len(psi_df[psi_df['Stability']=='Monitor'])}")
print(f"  Unstable (PSI > 0.20)  : {len(psi_df[psi_df['Stability']=='Unstable'])}")
print()
print(psi_df.to_string(index=False))

"""### Step 5.5 — Combined Drift Detection Report and Summary"""

fig, axes = plt.subplots(1, 3, figsize=(20, 7))

# KS Test results
ks_top   = ks_df.head(20)
colors_ks = ['crimson' if d=='YES' else 'steelblue' for d in ks_top['Drift Detected']]
axes[0].barh(ks_top['Feature'], ks_top['KS Statistic'], color=colors_ks, edgecolor='black', linewidth=0.5)
axes[0].set_title('KS Test — Top 20 Features\n(Bonferroni-corrected)', fontweight='bold')
axes[0].set_xlabel('KS Statistic (higher = more drift)')
axes[0].invert_yaxis()
axes[0].legend(handles=[Patch(color='crimson',label='Drift: YES'), Patch(color='steelblue',label='Drift: NO')])

# Chi-Square results
colors_chi = ['crimson' if d=='YES' else 'steelblue' for d in chi_df['Drift Detected']]
axes[1].barh(chi_df['Feature'], chi_df['Chi2 Statistic'], color=colors_chi, edgecolor='black', linewidth=0.5)
axes[1].set_title('Chi-Square Test — Categorical Features\n(Bonferroni-corrected)', fontweight='bold')
axes[1].set_xlabel('Chi-Square Statistic')
axes[1].invert_yaxis()

# PSI results
colors_psi = ['crimson' if s=='Unstable' else 'orange' if s=='Monitor' else 'steelblue' for s in psi_df['Stability']]
axes[2].barh(psi_df['Feature'], psi_df['PSI'], color=colors_psi, edgecolor='black', linewidth=0.5)
axes[2].axvline(x=0.20, color='black', linestyle='--', linewidth=1.5, label='Unstable (0.20)')
axes[2].axvline(x=0.10, color='grey',  linestyle='--', linewidth=1.5, label='Monitor (0.10)')
axes[2].set_title('PSI — Top 20 Numerical Features\n(Fixed-Width Bins)', fontweight='bold')
axes[2].set_xlabel('PSI Value')
axes[2].invert_yaxis()
axes[2].legend(fontsize=9)

plt.suptitle('Combined Drift Detection Report — Phase 5', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

# Summary
ks_drifted  = ks_df[ks_df['Drift Detected']=='YES']['Feature'].tolist()
chi_drifted = chi_df[chi_df['Drift Detected']=='YES']['Feature'].tolist()
psi_drifted = psi_df[psi_df['Stability']=='Unstable']['Feature'].tolist()
all_drifted = sorted(set(ks_drifted) | set(chi_drifted) | set(psi_drifted))

print("  COMBINED DRIFT DETECTION SUMMARY")
print(f"  KS Test    — drifted features    : {len(ks_drifted)} / {len(ks_df)}")
print(f"  Chi-Square — drifted features    : {len(chi_drifted)} / {len(chi_df)}")
print(f"  PSI        — unstable features   : {len(psi_drifted)} / {len(psi_df)}")
print(f"  Total unique features flagged    : {len(all_drifted)}")
print()
print("  Features flagged by multiple tests (highest confidence):")
multi_flagged = sorted(set(ks_drifted) & (set(chi_drifted) | set(psi_drifted)))
for f in multi_flagged[:10]:
    print(f"    → {f}")

"""---
## Phase 6 — Human-in-the-Loop Validation

### Why Human Validation is Necessary

Statistical drift detection identifies features whose distributions have changed mathematically — but not all statistical drift is operationally significant. Consider these scenarios:

- A feature may drift statistically but have **no impact on fraud detection** (e.g. a minor shift in an anonymised V-feature)
- A feature may show only **moderate PSI** but be a **critical fraud signal** that domain experts know is important
- Statistical tests cannot distinguish between drift caused by **seasonal patterns** (acceptable, predictable) vs **genuine behavioural change** (requires retraining)

A domain expert — someone with knowledge of the fraud detection business, the customer base, and the feature engineering — can apply this contextual knowledge to make a more informed retraining decision.

### How the Widget Works

Below, an **interactive form** displays each drifted feature alongside its statistical evidence (KS statistic, PSI, Chi-Square result, drift direction, and whether it was flagged by multiple tests). The expert clicks **YES** (business-critical, retraining needed) or **NO** (acceptable, no action needed) for each feature, then presses **Submit**.

This is genuine Human-in-the-Loop validation — the retraining decision in Phase 7 is directly determined by what the expert inputs here.

---

### Step 6.1 — Prepare Feature Information for Expert Review
"""

# Collect all drifted features from all three tests
# Sort alphabetically to ensure reproducible, consistent ordering every run
# Cap at 15 features for human review — this follows HCI guidelines on cognitive load:
# presenting more than 15 items in a single review session degrades decision quality
# (Miller, 1956; Sweller, 1988 — cognitive load theory). In production systems, feature
# review queues are typically limited to 10-20 items per review cycle.
priority_features = sorted(list(set(psi_drifted) | set(chi_drifted) | set(ks_drifted[:10])))[:15]

print("  FEATURES SELECTED FOR HUMAN EXPERT REVIEW")
print(f"  Total features flagged by drift tests : {len(all_drifted)}")
print(f"  Features presented to expert          : {len(priority_features)}")
print(f"  Selection criteria                    : PSI unstable OR Chi2 drifted OR top KS drifted")
print(f"  Ordering                              : Alphabetical (reproducible across runs)")
print()
print(f"  {'Feature':<20} {'KS Stat':>10} {'PSI':>8} {'Chi2':>10} {'Multi-test?':>13}")
print(f"  {'-'*65}")

for feat in priority_features:
    ks_val   = ks_df[ks_df['Feature']==feat]['KS Statistic'].values
    psi_val  = psi_df[psi_df['Feature']==feat]['PSI'].values
    chi_val  = chi_df[chi_df['Feature']==feat]['Chi2 Statistic'].values
    ks_str   = f"{ks_val[0]:.4f}"  if len(ks_val)  > 0 else "N/A"
    psi_str  = f"{psi_val[0]:.4f}" if len(psi_val) > 0 else "N/A"
    chi_str  = f"{chi_val[0]:.1f}" if len(chi_val) > 0 else "N/A"
    multi    = "YES" if feat in multi_flagged else "no"
    print(f"  {feat:<20} {ks_str:>10} {psi_str:>8} {chi_str:>10} {multi:>13}")

"""### Step 6.2 — Interactive Human Expert Validation Widget

Run this cell to launch the interactive review form. For each feature, you will see:
- Feature name
- KS Statistic (how different the distributions are)
- PSI value (magnitude of shift)
- Chi-Square result (for categorical features)
- Whether it was flagged by multiple tests (higher confidence of real drift)
- Drift direction (whether the mean has increased or decreased in candidate data)

**Instructions:**
1. Read the information for each feature carefully
2. Click **YES — Critical** if the feature's drift is business-critical and retraining is needed
3. Click **NO — Acceptable** if the drift is acceptable and no immediate action is required
4. When all decisions are made, press **Submit Expert Decisions**
5. Then run the next cell to see the retraining decision
"""

toggle_widgets   = {}
rows             = []
expert_decisions = {}  # reset on each run — submit widget before proceeding

for feat in priority_features:
    ks_val    = ks_df[ks_df['Feature']==feat]['KS Statistic'].values
    psi_val   = psi_df[psi_df['Feature']==feat]['PSI'].values
    chi_val   = chi_df[chi_df['Feature']==feat]['Chi2 Statistic'].values
    chi_drift = chi_df[chi_df['Feature']==feat]['Drift Detected'].values

    # Compute drift direction from reference to candidate (mean shift)
    if feat in ref.columns and feat in cand.columns:
        ref_mean  = ref[feat].mean()
        cand_mean = cand[feat].mean()
        direction = f"↑ +{round(cand_mean-ref_mean,3)}" if cand_mean > ref_mean else f"↓ {round(cand_mean-ref_mean,3)}"
    else:
        direction = "N/A"

    ks_str  = f"KS={ks_val[0]:.4f}"  if len(ks_val)  > 0 else "KS=N/A"
    psi_str = f"PSI={psi_val[0]:.4f}" if len(psi_val) > 0 else "PSI=N/A"
    chi_str = f"Chi2={chi_val[0]:.1f} ({'DRIFTED' if len(chi_drift)>0 and chi_drift[0]=='YES' else 'stable'})" if len(chi_val)>0 else ""
    multi   = " ⚠ MULTI-TEST" if feat in multi_flagged else ""

    info_html = (
        f"<div style='padding:6px 0; border-bottom:1px solid #eee'>"
        f"<b style='font-size:14px'>{feat}</b>{multi}<br>"
        f"<span style='color:#555;font-size:12px'>"
        f"{ks_str} &nbsp;|&nbsp; {psi_str}"
        f"{' &nbsp;|&nbsp; ' + chi_str if chi_str else ''}"
        f" &nbsp;|&nbsp; Direction: <b>{direction}</b>"
        f"</span></div>"
    )

    label  = widgets.HTML(value=info_html, layout=widgets.Layout(width='520px'))
    toggle = widgets.ToggleButtons(
        options=['YES — Critical (Retrain)', 'NO — Acceptable'],
        value='NO — Acceptable',
        button_style='',
        layout=widgets.Layout(width='340px')
    )
    toggle_widgets[feat] = toggle
    rows.append(widgets.HBox([label, toggle],
                             layout=widgets.Layout(align_items='center', margin='4px 0')))

submit_btn  = widgets.Button(
    description='Submit Expert Decisions',
    button_style='success',
    icon='check',
    layout=widgets.Layout(width='260px', height='40px', margin='20px 0')
)
output_area = widgets.Output()

def on_submit(b):
    with output_area:
        clear_output()
        for feat, tog in toggle_widgets.items():
            expert_decisions[feat] = 'YES' if 'YES' in tog.value else 'NO'

        confirmed = [f for f, d in expert_decisions.items() if d == 'YES']
        rejected  = [f for f, d in expert_decisions.items() if d == 'NO']

        print("  EXPERT DECISIONS RECORDED SUCCESSFULLY")
        print(f"  Total features reviewed          : {len(expert_decisions)}")
        print(f"  Confirmed business-critical (YES): {len(confirmed)}")
        print(f"  Accepted as non-critical (NO)    : {len(rejected)}")
        print()
        if confirmed:
            print("  Critical features (will trigger retraining if above threshold):")
            for f in confirmed:
                print(f"    ✓ {f}")
        if rejected:
            print()
            print("  Accepted features (drift noted but not actionable):")
            for f in rejected:
                print(f"    ✗ {f}")
        print()
        print("  >> Decisions recorded. Now run the next cell.")

submit_btn.on_click(on_submit)

header = widgets.HTML(
    value="<h3 style='margin:10px 0'>🧑‍💼 Human Expert Review — Phase 6</h3>"
          "<p style='color:#444'>Review each drifted feature below. "
          "Select YES if the drift is business-critical. "
          "⚠ MULTI-TEST = flagged by more than one statistical test (higher confidence).</p>"
)

display(widgets.VBox(
    [header] + rows + [submit_btn, output_area],
    layout=widgets.Layout(padding='10px')
))

"""### Step 6.3 — Retraining Decision Based on Expert Input

Run this cell **after** submitting your decisions in the widget above.

**Threshold Justification:** The retraining threshold is set to **20% of reviewed features**. This means: if more than 1 in 5 of the reviewed features are confirmed as business-critical by the expert, the drift is considered systemic and widespread enough to warrant retraining. This follows the principle used in production ML monitoring systems (Klaise et al., 2021 — Alibi Detect) where a configurable proportion threshold triggers automated actions. The `max(3, ...)` ensures the threshold is never below 3, preventing retraining from being triggered by a single feature in small review sets.
"""

# Guard: ensure widget in the previous cell was submitted before running this cell
if not expert_decisions:
    print("⚠  No expert decisions recorded.")
    print("   Please submit the widget in the cell above first, then re-run this cell.")
    raise SystemExit(0)

total_reviewed           = len(priority_features)
threshold_for_retraining = max(3, int(total_reviewed * 0.20))

confirmed = [f for f, d in expert_decisions.items() if d == 'YES']
rejected  = [f for f, d in expert_decisions.items() if d == 'NO']

print("  RETRAINING DECISION REPORT")
print(f"  Total features reviewed      : {total_reviewed}")
print(f"  Confirmed critical (YES)     : {len(confirmed)}")
print(f"  Accepted (NO)                : {len(rejected)}")
print(f"  Retraining threshold         : {threshold_for_retraining} features")
print(f"  Threshold rationale          : 20% of {total_reviewed} reviewed = {int(total_reviewed*0.20)}")
print(f"                                 (min 3 to avoid single-feature triggers)")
print()

if len(confirmed) >= threshold_for_retraining:
    decision = "RETRAIN"
    print("  ▶ DECISION: RETRAINING REQUIRED")
    print(f"  Reason: {len(confirmed)} business-critical features confirmed drifted,")
    print(f"          exceeding the threshold of {threshold_for_retraining}.")
    print("          The model will be retrained on the new data in Phase 7.")
else:
    decision = "MONITOR"
    print("  ▶ DECISION: MONITOR ONLY")
    print(f"  Reason: Only {len(confirmed)} critical features confirmed drifted,")
    print(f"          below the threshold of {threshold_for_retraining}.")
    print("          Continue monitoring; schedule retraining at next review cycle.")

# Visualisation
fig, axes = plt.subplots(1, 2, figsize=(13, 5))

axes[0].pie(
    [len(confirmed), max(len(rejected), 0)],
    labels=[f'Critical — YES ({len(confirmed)})', f'Acceptable — NO ({len(rejected)})'],
    colors=['crimson', 'steelblue'],
    autopct='%1.1f%%', startangle=90,
    wedgeprops={'edgecolor': 'white', 'linewidth': 2}
)
axes[0].set_title('Expert Validation — Decision Breakdown', fontweight='bold')

all_feats   = confirmed + rejected
all_colors  = ['crimson']*len(confirmed) + ['steelblue']*len(rejected)
if all_feats:
    axes[1].barh(all_feats, [1]*len(all_feats), color=all_colors, edgecolor='black', linewidth=0.5)
    axes[1].set_title('Feature-Level Expert Decisions', fontweight='bold')
    axes[1].set_xlabel('Decision')
    axes[1].set_xlim(0, 1.5)
    axes[1].legend(handles=[Patch(color='crimson',label='Critical (YES)'),
                             Patch(color='steelblue',label='Acceptable (NO)')])

plt.suptitle('Human-in-the-Loop Validation Summary — Phase 6',
             fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

"""---
## Phase 7 — Model Retraining

Based on the human expert's validation in Phase 6, retraining has been triggered. In this phase we retrain the LightGBM model on the **candidate data** — the newer transactions that the baseline model had not seen during training.

### Why retrain on candidate data only (not reference + candidate combined)?

The candidate data represents the **current distribution** of transactions. When data drift has been confirmed and validated by a human expert, the candidate data better reflects the patterns the model will encounter going forward. Including the older reference data risks diluting these new patterns and partially reintroducing the outdated distribution that caused the performance degradation.

This is a deliberate design choice consistent with **sliding window retraining** approaches used in production ML monitoring systems (Klaise et al., 2021 — Alibi Detect), where only recent data is used for retraining after a confirmed drift event. An alternative — combining reference and candidate — would be appropriate when drift is gradual rather than abrupt.

### Note on hyperparameters

The same hyperparameter configuration is used for retraining. In a full production system, hyperparameter search would be re-run after retraining. However, for this dissertation the focus is on demonstrating the **HITL drift detection and retraining pipeline** rather than hyperparameter optimisation.

---

### Step 7.1 — Load Candidate Data and Retrain
"""

# Redefine thresholds here to ensure this cell can be run independently
thresholds = np.arange(0.01, 0.50, 0.01)

cand = pd.read_csv('/content/drive/MyDrive/fraud_project/candidate.csv', low_memory=False)
drop_cols = [c for c in ['TransactionID', 'TransactionDT', 'isFraud', 'DT_bin'] if c in cand.columns]
X_cand_full = cand.drop(columns=drop_cols)   # keep full candidate set for fair final comparison
y_cand_full = cand['isFraud']
del cand; gc.collect()

X = X_cand_full.copy()
y = y_cand_full.copy()
X_train, X_val_ret, y_train, y_val_ret = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)
del X, y; gc.collect()

scale_r = round((y_train == 0).sum() / y_train.sum(), 2)

print("  RETRAINING DATA SUMMARY")
print(f"  Training samples   : {len(X_train):,}")
print(f"  Validation samples : {len(X_val_ret):,}")
print(f"  Fraud in train     : {y_train.sum():,}")
print(f"  Legit in train     : {(y_train==0).sum():,}")
print(f"  scale_pos_weight   : {scale_r}")
print()

lgb_retrained = lgb.LGBMClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=8,
    num_leaves=31,
    scale_pos_weight=scale_r,
    random_state=42,
    n_jobs=-1,
    verbose=-1
)

print("Retraining LightGBM on candidate (production) data...")
start = time.time()
lgb_retrained.fit(
    X_train, y_train,
    eval_set=[(X_val_ret, y_val_ret)],
    callbacks=[
        lgb.early_stopping(stopping_rounds=30, verbose=False),
        lgb.log_evaluation(50)
    ]
)
elapsed = round(time.time() - start, 2)
del X_train, y_train; gc.collect()
print(f"Retraining complete in {elapsed} seconds.")

"""### Step 7.2 — Evaluate Retrained Model"""

y_pred_proba_ret = lgb_retrained.predict_proba(X_val_ret)[:, 1]

# Apply same F1-maximisation threshold method for fair comparison
f1_scores_ret      = [f1_score(y_val_ret, (y_pred_proba_ret >= t).astype(int)) for t in thresholds]
best_threshold_ret = thresholds[np.argmax(f1_scores_ret)]
y_pred_ret         = (y_pred_proba_ret >= best_threshold_ret).astype(int)

roc_ret       = roc_auc_score(y_val_ret, y_pred_proba_ret)
precision_ret = precision_score(y_val_ret, y_pred_ret)
recall_ret    = recall_score(y_val_ret, y_pred_ret)
f1_ret        = f1_score(y_val_ret, y_pred_ret)

print("  RETRAINED MODEL EVALUATION")
print(f"  ROC-AUC   : {round(roc_ret, 4)}")
print(f"  Precision : {round(precision_ret, 4)}")
print(f"  Recall    : {round(recall_ret, 4)}")
print(f"  F1-Score  : {round(f1_ret, 4)}")
print(f"  Threshold : {round(best_threshold_ret, 2)}  (F1-maximised)")
print()
print(classification_report(y_val_ret, y_pred_ret, target_names=['Legitimate', 'Fraudulent']))

y_cand_proba_ret = lgb_retrained.predict_proba(X_cand_full)[:, 1]
roc_ret_full     = roc_auc_score(y_cand_full, y_cand_proba_ret)

print("  RETRAINED MODEL — FULL CANDIDATE SET EVALUATION")
print(f"  ROC-AUC on full candidate set : {round(roc_ret_full, 4)}")
print("  (This score is used in the final pipeline comparison")
print("   to ensure a like-for-like comparison with the baseline)")

"""### Step 7.3 — Full Pipeline Performance Comparison

This is the central result of the dissertation pipeline. We compare performance across three stages:

1. **Baseline on Reference** — How well the model performs on the data it was trained on
2. **Baseline on Candidate** — How performance degrades after data drift occurs
3. **Retrained on Candidate** — How performance recovers after human-validated retraining

**Important methodological note:** All three stages are evaluated on their respective held-out sets. Crucially, Stages 2 and 3 are both evaluated on the **full candidate dataset** — the same population — ensuring that the comparison between the degraded baseline and the retrained model is fair and not confounded by different test set compositions.
"""

# Compute retrained model metrics on the FULL candidate set for fair comparison
# (mirrors how baseline metrics in Cell 33 used the full X_cand / y_cand)
y_cand_pred_ret_full = (y_cand_proba_ret >= best_threshold_ret).astype(int)
precision_ret_full   = precision_score(y_cand_full, y_cand_pred_ret_full)
recall_ret_full      = recall_score(y_cand_full, y_cand_pred_ret_full)
f1_ret_full          = f1_score(y_cand_full, y_cand_pred_ret_full)

baseline_scores  = [round(roc_ref,4), round(precision_ref,4), round(recall_ref,4), round(f1_ref,4)]
retrained_scores = [round(roc_ret_full,4), round(precision_ret_full,4), round(recall_ret_full,4), round(f1_ret_full,4)]
metrics_list     = ['ROC-AUC', 'Precision', 'Recall', 'F1-Score']
x = range(len(metrics_list)); width = 0.35

fig, axes = plt.subplots(1, 2, figsize=(15, 6))

# Grouped bar: baseline vs retrained
axes[0].bar([i-width/2 for i in x], baseline_scores,  width, label='Baseline',  color='steelblue', edgecolor='black')
axes[0].bar([i+width/2 for i in x], retrained_scores, width, label='Retrained', color='green', edgecolor='black')
axes[0].set_title('Baseline vs Retrained — All Metrics', fontweight='bold')
axes[0].set_xticks(list(x)); axes[0].set_xticklabels(metrics_list, fontsize=12)
axes[0].set_ylabel('Score'); axes[0].set_ylim(0, 1.05); axes[0].legend(fontsize=11)
for i, (b, r) in enumerate(zip(baseline_scores, retrained_scores)):
    axes[0].text(i-width/2, b+0.01, str(b), ha='center', fontsize=9, fontweight='bold')
    axes[0].text(i+width/2, r+0.01, str(r), ha='center', fontsize=9, fontweight='bold')

roc_scores_full = [round(roc_ref,4), round(roc_cand,4), round(roc_ret_full,4)]
stage_labels    = ['Baseline\n(Reference Data)', 'Baseline\n(Candidate Data)', 'Retrained\n(Candidate Data)']
bar_colors      = ['steelblue', 'crimson', 'green']
axes[1].bar(stage_labels, roc_scores_full, color=bar_colors, edgecolor='black')
axes[1].set_title('ROC-AUC — Full Pipeline: Drift → Retraining', fontweight='bold')
axes[1].set_ylabel('ROC-AUC Score')
axes[1].set_ylim(min(roc_scores_full) - 0.03, max(roc_scores_full) + 0.03)
for i, v in enumerate(roc_scores_full):
    axes[1].text(i, v + 0.003, str(v), ha='center', fontsize=12, fontweight='bold')

plt.suptitle('Phase 7 — Retraining Impact Analysis', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

print("  FULL PIPELINE PERFORMANCE SUMMARY")
print(f"  Stage 1 — Baseline on Reference  : ROC-AUC = {round(roc_ref, 4)}")
print(f"  Stage 2 — Baseline on Candidate  : ROC-AUC = {round(roc_cand, 4)}  ({round(roc_cand-roc_ref,4):+})")
print(f"  Stage 3 — Retrained on Candidate : ROC-AUC = {round(roc_ret_full, 4)}  ({round(roc_ret_full-roc_cand,4):+})  [evaluated on full candidate set]")
print()
print(f"  Drift-induced degradation        : {round(roc_cand-roc_ref,4):+}")
print(f"  Retraining recovery              : {round(roc_ret_full-roc_cand,4):+}")
print(f"  Net improvement over degraded    : {round(roc_ret_full-roc_cand,4):+}")
print()
print("  Note: Stage 3 ROC-AUC is evaluated on the full candidate set")
print("  (same as Stage 2) to ensure a fair, like-for-like comparison.")
print(f"  (Retrained model internal val ROC-AUC: {round(roc_ret, 4)} — on 20% held-out split)")
print()
print("  Conclusion: The Human-in-the-Loop drift detection and")
print("  retraining pipeline successfully recovered model performance")
print("  after data drift was detected and validated by a domain expert.")

# Save retrained model
joblib.dump(lgb_retrained, '/content/drive/MyDrive/fraud_project/lgb_retrained_model.pkl')
print()
print("Retrained model saved to Drive.")

